name: Java CI with Maven

on:
  push:
    branches: [ "feature/bootstrap-library-app" ]
  pull_request:
    branches: [ "feature/bootstrap-library-app" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      
      - name: Setting up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build project
        run: mvn clean compile

      - name: Run unit tests on project
        run: mvn test

      - name: Run integration tests on project
        run: mvn verify

      - name: Run project
        run: mvn spring-boot:run
