name: Java CI with Maven

on:
  push:
    branches: [ "feature/bootstrap-library-app" ]
  pull_request:
    branches: [ "feature/bootstrap-library-app" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
      - uses: actions/checkout@v2
      
      - name: Setting up java
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'openjdk'

      - name: Setting up Maven
      - uses: actions/setup-maven@v2
        with:
          maven-version: 3.9.4

  build:

    runs-on: ubuntu-latest
    needs: setup
    
    steps:
      - name: Build project
        run: mvn clean compile

  test:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Run unit tests on project
        run: mvn test

  verify:

    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Run integration tests on project
        run: mvn verify

  run_project:

    runs-on: ubuntu-latest
    needs: verify
    
    steps:
      - name: Run project
        run: mvn spring-boot:run
